development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: diary_development
      identity_map_enabled: true

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: diary_test
      identity_map_enabled: true

